
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer Lalr__create_buffer
#define yy_delete_buffer Lalr__delete_buffer
#define yy_flex_debug Lalr__flex_debug
#define yy_init_buffer Lalr__init_buffer
#define yy_flush_buffer Lalr__flush_buffer
#define yy_load_buffer_state Lalr__load_buffer_state
#define yy_switch_to_buffer Lalr__switch_to_buffer
#define yyin Lalr_in
#define yyleng Lalr_leng
#define yylex Lalr_lex
#define yylineno Lalr_lineno
#define yyout Lalr_out
#define yyrestart Lalr_restart
#define yytext Lalr_text
#define yywrap Lalr_wrap
#define yyalloc Lalr_alloc
#define yyrealloc Lalr_realloc
#define yyfree Lalr_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE Lalr_restart(Lalr_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t Lalr_leng;

extern FILE *Lalr_in, *Lalr_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up Lalr_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up Lalr_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via Lalr_restart()), so that the user can continue scanning by
	 * just pointing Lalr_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when Lalr_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t Lalr_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow Lalr_wrap()'s to do buffer switches
 * instead of setting up a fresh Lalr_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void Lalr_restart (FILE *input_file  );
void Lalr__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE Lalr__create_buffer (FILE *file,int size  );
void Lalr__delete_buffer (YY_BUFFER_STATE b  );
void Lalr__flush_buffer (YY_BUFFER_STATE b  );
void Lalr_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void Lalr_pop_buffer_state (void );

static void Lalr_ensure_buffer_stack (void );
static void Lalr__load_buffer_state (void );
static void Lalr__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER Lalr__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE Lalr__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE Lalr__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE Lalr__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *Lalr_alloc (yy_size_t  );
void *Lalr_realloc (void *,yy_size_t  );
void Lalr_free (void *  );

#define yy_new_buffer Lalr__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        Lalr_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Lalr__create_buffer(Lalr_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        Lalr_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Lalr__create_buffer(Lalr_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *Lalr_in = (FILE *) 0, *Lalr_out = (FILE *) 0;

typedef int yy_state_type;

extern int Lalr_lineno;

int Lalr_lineno = 1;

extern char *Lalr_text;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr Lalr_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up Lalr_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	Lalr_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[469] =
    {   0,
        0,    0,   64,   62,   61,   60,   62,   49,   62,   62,
       52,   56,   44,   62,   43,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   61,   49,   62,   61,   60,    0,
        0,    0,    0,    0,    0,    0,    0,   42,   56,   55,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       61,    0,   59,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   59,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   57,   57,   57,   57,   57,   57,   57,
       57,   57,    0,    0,    0,    0,   15,    0,    0,    1,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   47,   57,   57,   57,   57,
       57,   57,   51,   57,   58,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       16,    0,    0,    2,    0,    0,    0,    0,    0,    0,
       57,   57,   50,   45,   48,   57,   57,   58,    0,    0,
       39,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   41,   57,   57,   57,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    5,    0,
       17,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   57,   57,   57,    0,   40,    0,
       13,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    6,    0,
       18,    0,   46,   57,   57,   11,    7,    0,   29,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   14,
        0,    0,    0,    0,    0,    0,    0,    0,   53,   57,
        9,    0,    0,    0,    0,    0,    0,    0,    3,   19,

       12,    8,    0,   30,    0,    0,    0,    0,    0,    0,
        0,    0,   54,    0,    0,    0,    0,    0,    0,    0,
       10,    0,    0,    0,    0,    0,    0,    0,    4,   20,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   25,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   26,
        0,    0,    0,    0,   23,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   33,    0,    0,
        0,    0,    0,    0,   24,    0,    0,    0,    0,    0,
       21,   31,    0,    0,    0,   34,    0,    0,    0,    0,
        0,    0,   27,    0,   22,   32,    0,    0,    0,    0,
        0,    0,   28,    0,    0,    0,    0,   37,    0,    0,
        0,    0,   38,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   35,    0,   36,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    1,    1,    7,    1,    8,    1,    1,    1,
        1,    1,    1,    1,    9,   10,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,   13,    1,
       14,   15,   16,    1,   17,   18,   18,   18,   19,   18,
       20,   18,   21,   18,   18,   22,   23,   24,   25,   26,
       18,   27,   28,   29,   18,   18,   18,   18,   30,   18,
        1,    1,    1,    1,   31,    1,   32,   33,   34,   35,

       36,   37,   18,   38,   39,   18,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   18,   51,   18,
       52,   18,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[53] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3
    } ;

static yyconst flex_uint16_t yy_base[472] =
    {   0,
        0,   51,  523,  524,   57,  524,  519,   58,   46,  506,
      524,  509,  524,  504,  524,    0,  495,  490,  491,  486,
      472,   34,  464,  465,   77,   83,   89,   90,  524,  469,
       31,   70,  485,  483,  461,   52,   82,  524,  496,  524,
        0,  480,  488,  480,  486,  457,  454,  459,  467,  466,
      108,  114,    0,  458,  451,  459,  445,  457,  461,  450,
      463,  460,  444,  440,  454,  443,  435,   90,  458,  456,
      434,   62,  451,  456,  447,  448,  427,  427,  433,  424,
      429,    0,  428,  421,  426,  420,  425,   28,  419,  446,
       90,  429,  421,  419,  416,  424,  428,  417,  430,  427,

      411,  407,  421,  422,  428,  431,  430,  396,  398,  402,
      409,  396,  407,  403,  392,  388,  524,  387,  389,  524,
      406,  411,   97,   73,  407,  386,  384,  390,   58,  384,
      411,  101,  394,  386,  384,    0,  409,  402,  396,  411,
      410,  370,    0,  381,    0,  376,  370,  375,  374,  383,
      393,  386,  385,  367,  360,  371,  374,  371,  367,  366,
      524,  352,  354,  524,  371,  376,  103,  100,  372,  351,
      371,  371,    0,  524,  524,  360,  346,    0,  358,  341,
      524,  359,  342,   93,  371,  358,  347,  351,  338,  336,
      335,  334,  339,  339,  348,  358,  351,  350,  332,  325,

      336,  339,  336,  332,    0,  341,  322,  329,  319,  324,
      321,  328,  327,  326,  330,  332,  318,  310,  524,  318,
      524,  317,  319,  321,  304,   96,  333,  320,  309,  313,
      300,  298,  297,  296,  314,  295,  298,  293,  524,  299,
      524,  296,  296,  107,  285,  292,  286,  290,  289,  284,
      287,  294,  293,  292,  296,  298,  284,  276,  524,  284,
      524,  283,    0,  309,  277,  524,  271,  269,  524,  290,
      269,  268,  272,  262,  273,  268,  267,  261,  267,  524,
      264,  264,  115,  253,  260,  254,  258,  257,  524,  252,
      524,  251,  267,  253,  264,  262,  258,  249,  524,  524,

      524,  244,  242,  524,  263,  242,  241,  245,  235,  246,
      241,  240,    0,  230,   98,  246,  237,  235,  231,  234,
      524,  228,  244,  230,  241,  239,  235,  226,  524,  524,
      227,  216,  218,  216,  217,  223,  215,  220,  209,  110,
      225,  216,  214,  210,  213,  224,  212,  221,  218,  212,
      202,  215,  216,  205,  194,  196,  194,  195,  201,  193,
      198,  191,  205,  188,  187,  186,  524,  190,  186,  201,
      189,  198,  195,  189,  179,  192,  193,  179,  179,  186,
      182,  181,  178,  178,  169,  183,  166,  165,  164,  524,
      168,  164,  178,  168,  524,  164,  163,  162,  157,  159,

      159,  166,  162,  161,  158,  158,  163,  524,  153,  152,
      151,  141,  160,  150,  524,  146,  145,  144,  139,  150,
      524,  524,  137,  142,  149,  524,  139,  138,  137,  127,
      130,  125,  524,  140,  524,  524,  127,  132,  121,  130,
      123,  118,  524,  127,  137,  115,  124,  524,  136,  121,
      129,  121,  524,  127,  107,  117,  110,  104,  120,  105,
      103,  107,   33,   34,  524,    6,  524,  524,   51,  158,
      161
    } ;

static yyconst flex_int16_t yy_def[472] =
    {   0,
      468,    1,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  469,  469,  469,  469,  469,
      469,  469,  469,  469,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      469,  469,  469,  469,  469,  469,  469,  469,  469,  469,
      468,  468,  470,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  469,  469,  469,  469,  469,  469,  469,  469,
      469,  470,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,

      468,  468,  468,  469,  469,  469,  469,  469,  469,  469,
      469,  469,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  469,  469,  469,  469,  469,
      469,  469,  469,  469,  471,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      469,  469,  469,  468,  468,  469,  469,  471,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,

      468,  468,  468,  468,  469,  469,  469,  469,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  469,  469,  469,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  469,  469,  469,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  469,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,

      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  469,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,

      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,    0,  468,  468,
      468
    } ;

static yyconst flex_uint16_t yy_nxt[577] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,    4,   13,   14,    4,   15,   16,   16,   17,   18,
       16,   16,   16,   19,   16,   16,   16,   20,   16,   16,
       16,   16,   16,   16,   16,   21,   22,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   23,   24,   16,
       16,   16,   25,   41,  467,  118,   26,   27,   28,   28,
       28,   28,   28,   28,   30,   56,   31,   32,   33,  466,
       34,   35,   47,   57,   36,  119,   37,   48,   51,   58,
       28,  465,   51,   52,   51,  162,   28,   64,   51,   52,
       53,   28,   53,   28,   53,   28,   59,  102,   65,  156,

       66,   60,   67,   68,   69,  163,   70,   71,  103,   51,
       72,   28,  122,   51,   52,   53,   97,   53,  153,   53,
      123,   98,  157,  166,  198,  332,  201,  213,  270,   54,
      253,  167,  271,  154,  464,  272,  305,  355,  463,  199,
      306,  214,  155,  307,  254,  333,  462,  461,  200,  202,
      460,  459,  458,  457,   54,  456,  455,  356,   82,  454,
       82,  178,  453,  178,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  438,  437,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,

      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,

      312,  311,  310,  309,  308,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  216,  215,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,

      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  165,
      164,  161,  160,  159,  158,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  130,  129,  128,
      127,  126,  125,  124,  121,  120,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  107,  106,  105,  104,
      101,  100,   99,   96,   95,   94,   93,   92,   91,   90,
       89,   88,   87,   86,   85,   84,   83,   81,   80,   79,

       78,   77,   76,   75,   74,   73,   39,   63,   62,   61,
       55,   50,   49,   46,   45,   44,   43,   42,   40,   39,
       38,   29,  468,    3,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468
    } ;

static yyconst flex_int16_t yy_chk[577] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,  469,  466,   88,    2,    2,    5,    8,
        5,    8,    5,    8,    9,   31,    9,    9,    9,  464,
        9,    9,   22,   31,    9,   88,    9,   22,   25,   31,
       25,  463,   25,   25,   26,  129,   26,   36,   26,   26,
       27,   28,   27,   28,   27,   28,   32,   72,   36,  124,

       37,   32,   37,   37,   37,  129,   37,   37,   72,   51,
       37,   51,   91,   51,   51,   52,   68,   52,  123,   52,
       91,   68,  124,  132,  167,  315,  168,  184,  244,   27,
      226,  132,  244,  123,  462,  244,  283,  340,  461,  167,
      283,  184,  123,  283,  226,  315,  460,  459,  167,  168,
      458,  457,  456,  455,   52,  454,  452,  340,  470,  451,
      470,  471,  450,  471,  449,  447,  446,  445,  444,  442,
      441,  440,  439,  438,  437,  434,  432,  431,  430,  429,
      428,  427,  425,  424,  423,  420,  419,  418,  417,  416,
      414,  413,  412,  411,  410,  409,  407,  406,  405,  404,

      403,  402,  401,  400,  399,  398,  397,  396,  394,  393,
      392,  391,  389,  388,  387,  386,  385,  384,  383,  382,
      381,  380,  379,  378,  377,  376,  375,  374,  373,  372,
      371,  370,  369,  368,  366,  365,  364,  363,  362,  361,
      360,  359,  358,  357,  356,  355,  354,  353,  352,  351,
      350,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  328,
      327,  326,  325,  324,  323,  322,  320,  319,  318,  317,
      316,  314,  312,  311,  310,  309,  308,  307,  306,  305,
      303,  302,  298,  297,  296,  295,  294,  293,  292,  290,

      288,  287,  286,  285,  284,  282,  281,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  268,  267,  265,
      264,  262,  260,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  243,  242,  240,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  225,  224,  223,  222,  220,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      183,  182,  180,  179,  177,  176,  172,  171,  170,  169,

      166,  165,  163,  162,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  144,
      142,  141,  140,  139,  138,  137,  135,  134,  133,  131,
      130,  128,  127,  126,  125,  122,  121,  119,  118,  116,
      115,  114,  113,  112,  111,  110,  109,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   99,   98,   97,   96,
       95,   94,   93,   92,   90,   89,   87,   86,   85,   84,
       83,   81,   80,   79,   78,   77,   76,   75,   74,   73,
       71,   70,   69,   67,   66,   65,   64,   63,   62,   61,
       60,   59,   58,   57,   56,   55,   54,   50,   49,   48,

       47,   46,   45,   44,   43,   42,   39,   35,   34,   33,
       30,   24,   23,   21,   20,   19,   18,   17,   14,   12,
       10,    7,    3,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int Lalr__flex_debug;
int Lalr__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *Lalr_text;
#define fe_parser_input Lalr_in
#include "Lalr.h"
#include "front/support.h"
#include "front/scan_support.h"
#include "front/parse_support.h"
#include "Lalr_y.h"
#undef YYLMAX
#define YYLMAX		(8*1024-1)

int Lalr_state_stack_depth=0;

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int Lalr_lex_destroy (void );

int Lalr_get_debug (void );

void Lalr_set_debug (int debug_flag  );

YY_EXTRA_TYPE Lalr_get_extra (void );

void Lalr_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *Lalr_get_in (void );

void Lalr_set_in  (FILE * _in_str  );

FILE *Lalr_get_out (void );

void Lalr_set_out  (FILE * _out_str  );

yy_size_t Lalr_get_leng (void );

char *Lalr_get_text (void );

int Lalr_get_lineno (void );

void Lalr_set_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int Lalr_wrap (void );
#else
extern int Lalr_wrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( Lalr_text, Lalr_leng, 1, Lalr_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( Lalr_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( Lalr_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, Lalr_in))==0 && ferror(Lalr_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(Lalr_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int Lalr_lex (void);

#define YY_DECL int Lalr_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after Lalr_text and Lalr_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( Lalr_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(Lalr_text[Lalr_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! Lalr_in )
			Lalr_in = stdin;

		if ( ! Lalr_out )
			Lalr_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			Lalr_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				Lalr__create_buffer(Lalr_in,YY_BUF_SIZE );
		}

		Lalr__load_buffer_state( );
		}

	{

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of Lalr_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 469 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 524 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{
  return hole_Lalr;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
{
  return start_Lalr;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
{
  return hole_Production;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
{
  return start_Production;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
{
  return hole_ProdRhs;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
{
  return start_ProdRhs;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
{
  return hole_LR_Symbol;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
{
  return start_LR_Symbol;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
{
  return hole_LR_Symbols;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
{
  return start_LR_Symbols;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
{
  return hole_Emptiness;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
{
  return start_Emptiness;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
{
  return hole_LR_state;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
{
  return start_LR_state;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
{
  return hole_Item;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
{
  return start_Item;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
{
  return hole_TermSet;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
{
  return start_TermSet;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
{
  return hole_Transition;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
{
  return start_Transition;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
{
  return hole_OPTMORE_Production;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
{
  return start_OPTMORE_Production;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
{
  return hole_OPTMORE_LR_state;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
{
  return start_OPTMORE_LR_state;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
{
  return hole_OPT_LR_Symbols;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
{
  return start_OPT_LR_Symbols;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
{
  return hole_OPT_questionmarksym;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
{
  return start_OPT_questionmarksym;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
{
  return hole_MORE_Item;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
{
  return start_MORE_Item;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
{
  return hole_OPTMORE_Transition;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
{
  return start_OPTMORE_Transition;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
{
  return hole_OPTMORE_LR_Symbol;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
{
  return start_OPTMORE_LR_Symbol;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
{
  return hole_OPT_followerscolonsym_TermSet;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
{
  return start_OPT_followerscolonsym_TermSet;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
{
  return hole_MORE_Identsym_spacesym;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
{
  return start_MORE_Identsym_spacesym;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
{
  Lalr_lval.Intsym_type = (Int)Get_sub_tree();
  return Intsym;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
{
  Lalr_lval.Identsym_type = (Ident)Get_sub_tree();
  return Identsym;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return GRAMMARsym;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return minusgreaterthansym;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return questionmarksym;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return semicolonsym;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return emptycolonsym;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return NON_EMPTYsym;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return EMPTYsym;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return firstcolonsym;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return spacesym;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return STATESsym;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return statesym;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return dotsym;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return followerscolonsym;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return transitionssym;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
{
  record_length (Lalr_leng); return equalsgreaterthansym;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
{
  Lalr_lval.Intsym_type = Encode_Int(Lalr_text);
  record_length (Lalr_leng); return Intsym;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
{
  Lalr_lval.Identsym_type = Encode_Ident(Lalr_text);
  record_length (Lalr_leng); return Identsym;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
{
  record_length (Lalr_leng);
  record_symbol (Lalr_leng,Lalr_text);
  update_line_and_fname(Lalr_text);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
{
  record_length (Lalr_leng);
  record_symbol (Lalr_leng,Lalr_text);
  update_line_and_fname(Lalr_text);
}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
{
  record_length (Lalr_leng);
  record_symbol (Lalr_leng,Lalr_text);
  new_input_line();
}
	YY_BREAK
case 61:
YY_RULE_SETUP
{
  record_length (Lalr_leng);
  record_symbol (Lalr_leng,Lalr_text);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
{ return NONSENSE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed Lalr_in at a new source and called
			 * Lalr_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = Lalr_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( Lalr_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * Lalr_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of Lalr_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					Lalr_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			Lalr_restart(Lalr_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) Lalr_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 469 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 469 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 468);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up Lalr_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					Lalr_restart(Lalr_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( Lalr_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve Lalr_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void Lalr_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        Lalr_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            Lalr__create_buffer(Lalr_in,YY_BUF_SIZE );
	}

	Lalr__init_buffer(YY_CURRENT_BUFFER,input_file );
	Lalr__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void Lalr__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		Lalr_pop_buffer_state();
	 *		Lalr_push_buffer_state(new_buffer);
     */
	Lalr_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	Lalr__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (Lalr_wrap()) processing, but the only time this flag
	 * is looked at is after Lalr_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void Lalr__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	Lalr_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE Lalr__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) Lalr_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Lalr__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) Lalr_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in Lalr__create_buffer()" );

	b->yy_is_our_buffer = 1;

	Lalr__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with Lalr__create_buffer()
 * 
 */
    void Lalr__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		Lalr_free((void *) b->yy_ch_buf  );

	Lalr_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a Lalr_restart() or at EOF.
 */
    static void Lalr__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	Lalr__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then Lalr__init_buffer was _probably_
     * called from Lalr_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void Lalr__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		Lalr__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void Lalr_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	Lalr_ensure_buffer_stack();

	/* This block is copied from Lalr__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from Lalr__switch_to_buffer. */
	Lalr__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void Lalr_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	Lalr__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		Lalr__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void Lalr_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)Lalr_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Lalr_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)Lalr_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Lalr_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE Lalr__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) Lalr_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Lalr__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	Lalr__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to Lalr_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       Lalr__scan_bytes() instead.
 */
YY_BUFFER_STATE Lalr__scan_string (yyconst char * yystr )
{
    
	return Lalr__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to Lalr_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE Lalr__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) Lalr_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in Lalr__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = Lalr__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in Lalr__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up Lalr_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		Lalr_text[Lalr_leng] = (yy_hold_char); \
		(yy_c_buf_p) = Lalr_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		Lalr_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int Lalr_get_lineno  (void)
{
        
    return Lalr_lineno;
}

/** Get the input stream.
 * 
 */
FILE *Lalr_get_in  (void)
{
        return Lalr_in;
}

/** Get the output stream.
 * 
 */
FILE *Lalr_get_out  (void)
{
        return Lalr_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t Lalr_get_leng  (void)
{
        return Lalr_leng;
}

/** Get the current token.
 * 
 */

char *Lalr_get_text  (void)
{
        return Lalr_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void Lalr_set_lineno (int  _line_number )
{
    
    Lalr_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see Lalr__switch_to_buffer
 */
void Lalr_set_in (FILE *  _in_str )
{
        Lalr_in = _in_str ;
}

void Lalr_set_out (FILE *  _out_str )
{
        Lalr_out = _out_str ;
}

int Lalr_get_debug  (void)
{
        return Lalr__flex_debug;
}

void Lalr_set_debug (int  _bdebug )
{
        Lalr__flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from Lalr_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    Lalr_in = stdin;
    Lalr_out = stdout;
#else
    Lalr_in = (FILE *) 0;
    Lalr_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * Lalr_lex_init()
     */
    return 0;
}

/* Lalr_lex_destroy is for both reentrant and non-reentrant scanners. */
int Lalr_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		Lalr__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		Lalr_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	Lalr_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * Lalr_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *Lalr_alloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *Lalr_realloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void Lalr_free (void * ptr )
{
			free( (char *) ptr );	/* see Lalr_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

int Lalr_wrap()
{ return 1; }

void Lalr_error(char *s)
{ if (Front_Parse_Error) Front_Parse_Error (s, Lalr_text);
}

