
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer doggy__create_buffer
#define yy_delete_buffer doggy__delete_buffer
#define yy_flex_debug doggy__flex_debug
#define yy_init_buffer doggy__init_buffer
#define yy_flush_buffer doggy__flush_buffer
#define yy_load_buffer_state doggy__load_buffer_state
#define yy_switch_to_buffer doggy__switch_to_buffer
#define yyin doggy_in
#define yyleng doggy_leng
#define yylex doggy_lex
#define yylineno doggy_lineno
#define yyout doggy_out
#define yyrestart doggy_restart
#define yytext doggy_text
#define yywrap doggy_wrap
#define yyalloc doggy_alloc
#define yyrealloc doggy_realloc
#define yyfree doggy_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE doggy_restart(doggy_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t doggy_leng;

extern FILE *doggy_in, *doggy_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up doggy_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up doggy_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via doggy_restart()), so that the user can continue scanning by
	 * just pointing doggy_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when doggy_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t doggy_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow doggy_wrap()'s to do buffer switches
 * instead of setting up a fresh doggy_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void doggy_restart (FILE *input_file  );
void doggy__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE doggy__create_buffer (FILE *file,int size  );
void doggy__delete_buffer (YY_BUFFER_STATE b  );
void doggy__flush_buffer (YY_BUFFER_STATE b  );
void doggy_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void doggy_pop_buffer_state (void );

static void doggy_ensure_buffer_stack (void );
static void doggy__load_buffer_state (void );
static void doggy__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER doggy__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE doggy__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE doggy__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE doggy__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *doggy_alloc (yy_size_t  );
void *doggy_realloc (void *,yy_size_t  );
void doggy_free (void *  );

#define yy_new_buffer doggy__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        doggy_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            doggy__create_buffer(doggy_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        doggy_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            doggy__create_buffer(doggy_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *doggy_in = (FILE *) 0, *doggy_out = (FILE *) 0;

typedef int yy_state_type;

extern int doggy_lineno;

int doggy_lineno = 1;

extern char *doggy_text;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr doggy_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up doggy_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	doggy_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[190] =
    {   0,
        0,    0,   68,   66,   65,   64,   66,   51,   66,   41,
       42,    9,   10,   11,   43,    5,   13,   66,   40,   60,
       18,   23,   36,   25,   37,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   12,
       16,   31,   28,   44,   59,    3,   17,    6,   52,   65,
       66,   65,   64,   33,    0,   61,    0,   29,   53,   14,
       56,   57,   60,   59,   45,   38,   34,   32,   35,   39,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   50,
       59,   46,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   30,   65,    0,   63,    0,    0,    0,

       26,   59,   59,   59,   59,   59,   59,   59,   59,   59,
        4,   59,   59,   59,   59,   59,   59,   59,   59,   63,
        0,    0,    0,   59,   59,   59,   49,   59,   59,   59,
       59,   59,   27,   59,   15,   59,   47,   58,   59,   59,
       59,    0,    0,    0,   59,   59,   59,   48,   59,   59,
       59,   55,   59,    1,   54,   59,   62,   59,   59,   59,
       59,   59,   59,   59,   22,   62,   59,   59,   59,   59,
       59,    7,   59,   59,   59,   59,   21,   59,   20,   59,
       59,   59,   24,    2,   59,   59,   19,    8,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   11,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   33,   33,   36,   37,   38,   39,   40,
       33,   41,   42,   43,   44,   45,   46,   47,   48,   33,
       49,   50,   51,   52,   53,   54,   55,   55,   56,   56,

       57,   55,   33,   33,   58,   33,   33,   59,   33,   60,
       33,   33,   33,   61,   33,   62,   33,   63,   33,   64,
       33,   33,   65,   66,   67,   68,    1,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,

       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69
    } ;

static yyconst YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        5,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    7,    6,    1,    3,
        1,    1,    6,    1,    4,    5,    5,    6,    6,    7,
        7,    7,    7,    7,    1,    1,    1,    1,    8
    } ;

static yyconst flex_uint16_t yy_base[197] =
    {   0,
        0,   68,  216,  565,   69,  565,  206,  158,   65,  565,
      169,  565,  565,  565,  565,  565,  149,  146,   60,   57,
      140,  565,   56,  131,   57,   64,   66,   69,   72,   74,
       78,   80,   96,   76,   98,  104,  106,  110,  108,  565,
      565,  565,  112,  565,  114,  565,   81,  565,  565,  135,
      102,  107,  565,  565,  107,  565,  116,  565,  565,  565,
      565,  565,  120,  125,  565,  565,  565,  565,  565,  565,
      132,  134,  139,  145,  147,  149,  151,  153,  156,  161,
      165,  169,  177,  174,  179,  181,  184,  187,  191,  193,
      198,  203,  205,  565,  227,  226,    0,   33,  225,    0,

      219,  221,  223,  226,  228,  230,  232,  236,  248,  250,
      252,  256,  258,  260,  263,  268,  271,  273,  275,    0,
       28,  283,  327,  284,  286,  288,  290,  292,  295,  297,
      300,  302,  305,  318,  320,  324,  329,  331,  344,  341,
      346,   18,  214,  401,  348,  350,  353,  358,  360,  369,
      371,  374,  376,  379,  381,  385,    0,  390,  392,  395,
      416,  403,  418,  405,  420,    0,  426,  432,  434,  440,
      442,  444,  446,  450,  452,  458,  462,  464,  469,  471,
      474,  476,  478,  480,  483,  487,  489,  491,  565,  525,
      529,  533,  539,  546,  551,  556

    } ;

static yyconst flex_int16_t yy_def[197] =
    {   0,
      189,    1,  189,  189,  189,  189,  189,  189,  190,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  191,
      189,  189,  189,  189,  189,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  189,
      189,  189,  192,  189,  192,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  190,  189,  193,  189,  189,  189,
      189,  189,  191,  192,  189,  189,  189,  189,  189,  189,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  189,  189,  189,  194,  189,  190,  195,

      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  194,
      189,  190,  190,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  189,  190,  190,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  196,  192,  192,  192,
      192,  192,  192,  192,  192,  196,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,    0,  189,
      189,  189,  189,  189,  189,  189

    } ;

static yyconst flex_uint16_t yy_nxt[635] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    4,   10,   11,
        4,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   27,   27,   32,   27,   33,   34,   35,   27,
       36,   37,   38,   27,   27,   39,   27,   27,   40,    4,
       41,   42,   43,   44,   27,   27,   45,   27,   27,   27,
       27,   27,   27,   27,   46,   47,   48,   49,    4,   50,
       52,   56,   52,   61,  157,   51,   63,   63,   62,   66,
       67,   69,   70,   71,   71,   71,   71,  142,   71,   71,
      121,   71,   71,   71,   71,   71,   71,   71,   71,   71,

       71,   73,   76,   97,   79,   97,   74,   75,   52,   77,
       52,   82,   80,   56,   57,   71,   71,   71,   71,   84,
       78,   81,   83,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   99,   95,   85,   52,   63,
       63,   92,   96,   89,   71,   71,   94,   86,   87,   88,
       90,   71,   71,   71,   71,   68,   57,   91,   71,   71,
       98,   65,  100,   60,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   59,   71,   71,   93,   58,  100,
       71,   71,   54,  103,   71,   71,  101,  102,   71,   71,
      104,  107,  105,   71,   71,  106,   71,   71,   71,   71,

       71,   71,  108,   71,   71,  109,   71,   71,   53,  110,
       71,   71,   71,   71,  113,  189,  112,   71,   71,  111,
       56,  115,   71,   71,   71,   71,  114,   97,   95,   97,
       52,   56,  189,  118,   96,  189,  116,  117,   71,   71,
       71,   71,   71,   71,  122,   71,   71,   71,   71,   71,
       71,   71,   71,  189,  126,   71,   71,  189,  127,  125,
      129,  124,  128,   57,  131,  189,  119,   71,   71,   71,
       71,   71,   71,  130,   57,   71,   71,   71,   71,   71,
       71,  132,   71,   71,   98,  133,  134,   71,   71,   56,
       71,   71,   71,   71,   71,   71,  189,  135,  138,  136,

      137,  139,  143,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,  140,   71,   71,   71,   71,  145,   71,
       71,   71,   71,  148,   71,   71,  189,  138,  147,  146,
      189,  141,   57,   56,  189,  149,  151,   71,   71,   71,
       71,  189,  150,   71,   71,  189,  144,  144,   71,   71,
       71,   71,  189,  144,  144,  144,  144,  144,  144,  152,
       71,   71,  153,   71,   71,   71,   71,   71,   71,   71,
       71,  155,   71,   71,  189,  158,   57,   71,   71,   71,
       71,  144,  144,  144,  189,  154,  189,  160,   71,   71,
       71,   71,  159,   71,   71,   71,   71,  161,   71,   71,

       71,   71,  189,  162,   71,   71,  156,   56,  163,   71,
       71,   71,   71,  189,   71,   71,  164,  189,  168,  189,
      144,  144,   71,   71,   71,   71,  189,  144,  144,  144,
      144,  144,  144,  167,  169,   71,   71,   71,   71,   71,
       71,  171,  170,  189,  165,   71,   71,  173,  172,  189,
       57,   71,   71,   71,   71,  144,  144,  144,  189,   71,
       71,   71,   71,   71,   71,   71,   71,  189,  174,   71,
       71,   71,   71,  189,  175,  177,  176,   71,   71,  178,
      180,   71,   71,   71,   71,  189,  181,  179,   71,   71,
       71,   71,  182,   71,   71,   71,   71,   71,   71,   71,

       71,  189,   71,   71,  189,  183,   71,   71,   71,   71,
       71,   71,  184,  187,  186,  189,  189,  189,  185,  189,
      189,  189,  189,  189,  188,   55,  189,   55,   55,   55,
       55,   55,   64,   64,   64,   64,   72,   72,   72,   72,
       55,   55,   55,  189,  189,   55,  120,  189,  120,  120,
      120,  120,  120,  120,  123,  123,  166,  189,  166,  166,
      166,  166,  166,  166,    3,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189
    } ;

static yyconst flex_int16_t yy_chk[635] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        5,    9,    5,   19,  142,    2,   20,   20,   19,   23,
       23,   25,   25,   26,   26,   27,   27,  121,   28,   28,
       98,   29,   29,   30,   30,   34,   34,   31,   31,   32,

       32,   26,   29,   51,   31,   51,   26,   28,   52,   30,
       52,   32,   31,   55,    9,   33,   33,   35,   35,   34,
       30,   31,   33,   36,   36,   37,   37,   39,   39,   38,
       38,   43,   43,   45,   45,   57,   50,   35,   50,   63,
       63,   39,   50,   38,   64,   64,   47,   36,   37,   37,
       38,   71,   71,   72,   72,   24,   55,   38,   73,   73,
       51,   21,   57,   18,   74,   74,   75,   75,   76,   76,
       77,   77,   78,   78,   17,   79,   79,   45,   11,   57,
       80,   80,    8,   75,   81,   81,   73,   74,   82,   82,
       76,   79,   77,   84,   84,   78,   83,   83,   85,   85,

       86,   86,   81,   87,   87,   83,   88,   88,    7,   84,
       89,   89,   90,   90,   87,    3,   86,   91,   91,   85,
      143,   89,   92,   92,   93,   93,   88,   96,   95,   96,
       95,   99,    0,   92,   95,    0,   90,   91,  101,  101,
      102,  102,  103,  103,   99,  104,  104,  105,  105,  106,
      106,  107,  107,    0,  104,  108,  108,    0,  105,  103,
      106,  102,  105,  143,  108,    0,   93,  109,  109,  110,
      110,  111,  111,  107,   99,  112,  112,  113,  113,  114,
      114,  109,  115,  115,   96,  110,  112,  116,  116,  122,
      117,  117,  118,  118,  119,  119,    0,  113,  116,  114,

      115,  117,  122,  124,  124,  125,  125,  126,  126,  127,
      127,  128,  128,  118,  129,  129,  130,  130,  124,  131,
      131,  132,  132,  128,  133,  133,    0,  130,  126,  125,
        0,  119,  122,  123,    0,  129,  132,  134,  134,  135,
      135,    0,  131,  136,  136,    0,  123,  123,  137,  137,
      138,  138,    0,  123,  123,  123,  123,  123,  123,  134,
      140,  140,  136,  139,  139,  141,  141,  145,  145,  146,
      146,  140,  147,  147,    0,  145,  123,  148,  148,  149,
      149,  123,  123,  123,    0,  139,    0,  147,  150,  150,
      151,  151,  146,  152,  152,  153,  153,  149,  154,  154,

      155,  155,    0,  150,  156,  156,  141,  144,  151,  158,
      158,  159,  159,    0,  160,  160,  153,    0,  159,    0,
      144,  144,  162,  162,  164,  164,    0,  144,  144,  144,
      144,  144,  144,  158,  160,  161,  161,  163,  163,  165,
      165,  162,  161,    0,  156,  167,  167,  164,  163,    0,
      144,  168,  168,  169,  169,  144,  144,  144,    0,  170,
      170,  171,  171,  172,  172,  173,  173,    0,  167,  174,
      174,  175,  175,    0,  168,  170,  169,  176,  176,  171,
      174,  177,  177,  178,  178,    0,  175,  173,  179,  179,
      180,  180,  176,  181,  181,  182,  182,  183,  183,  184,

      184,    0,  185,  185,    0,  178,  186,  186,  187,  187,
      188,  188,  180,  185,  182,    0,    0,    0,  181,    0,
        0,    0,    0,    0,  186,  190,    0,  190,  190,  190,
      190,  190,  191,  191,  191,  191,  192,  192,  192,  192,
      193,  193,  193,    0,    0,  193,  194,    0,  194,  194,
      194,  194,  194,  194,  195,  195,  196,    0,  196,  196,
      196,  196,  196,  196,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int doggy__flex_debug;
int doggy__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *doggy_text;
#define fe_parser_input doggy_in
#include "doggy.h"
#include "front/support.h"
#include "front/scan_support.h"
#include "front/parse_support.h"
#include "doggy_y.h"
#undef YYLMAX
#define YYLMAX		(8*1024-1)

int doggy_state_stack_depth=0;

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int doggy_lex_destroy (void );

int doggy_get_debug (void );

void doggy_set_debug (int debug_flag  );

YY_EXTRA_TYPE doggy_get_extra (void );

void doggy_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *doggy_get_in (void );

void doggy_set_in  (FILE * _in_str  );

FILE *doggy_get_out (void );

void doggy_set_out  (FILE * _out_str  );

yy_size_t doggy_get_leng (void );

char *doggy_get_text (void );

int doggy_get_lineno (void );

void doggy_set_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int doggy_wrap (void );
#else
extern int doggy_wrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( doggy_text, doggy_leng, 1, doggy_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( doggy_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( doggy_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, doggy_in))==0 && ferror(doggy_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(doggy_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int doggy_lex (void);

#define YY_DECL int doggy_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after doggy_text and doggy_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( doggy_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(doggy_text[doggy_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! doggy_in )
			doggy_in = stdin;

		if ( ! doggy_out )
			doggy_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			doggy_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				doggy__create_buffer(doggy_in,YY_BUF_SIZE );
		}

		doggy__load_buffer_state( );
		}

	{

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of doggy_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 190 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 565 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{
  record_length (doggy_leng); return TYPESsym;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
{
  record_length (doggy_leng); return ATTRIBUTESsym;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
{
  record_length (doggy_leng); return openchainsym;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
{
  record_length (doggy_leng); return OPRsym;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
{
  record_length (doggy_leng); return commasym;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
{
  record_length (doggy_leng); return closechainsym;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
{
  record_length (doggy_leng); return MACHINEsym;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
{
  record_length (doggy_leng); return DESCRIPTIONsym;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
{
  record_length (doggy_leng); return openparsym;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
{
  record_length (doggy_leng); return closeparsym;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
{
  record_length (doggy_leng); return starsym;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
{
  record_length (doggy_leng); return openbrksym;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
{
  record_length (doggy_leng); return minussym;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
{
  record_length (doggy_leng); return dotdotsym;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
{
  record_length (doggy_leng); return STEPsym;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
{
  record_length (doggy_leng); return closebrksym;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
{
  record_length (doggy_leng); return verticalbarsym;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
{
  record_length (doggy_leng); return colonsym;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
{
  record_length (doggy_leng); return COMMUTATIVEsym;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
{
  record_length (doggy_leng); return SUPPORTSsym;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
{
  record_length (doggy_leng); return EXTERNALsym;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
{
  record_length (doggy_leng); return externsym;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
{
  record_length (doggy_leng); return semicolonsym;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
{
  record_length (doggy_leng); return FUNCTIONSsym;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
{
  record_length (doggy_leng); return equalssym;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
{
  record_length (doggy_leng); return ANYsym;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
{
  record_length (doggy_leng); return NULLsym;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
{
  record_length (doggy_leng); return _sym;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
{
  record_length (doggy_leng); return candsym;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
{
  record_length (doggy_leng); return corsym;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
{
  record_length (doggy_leng); return hatsym;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
{
  record_length (doggy_leng); return eqsym;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
{
  record_length (doggy_leng); return neqsym;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
{
  record_length (doggy_leng); return lesym;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
{
  record_length (doggy_leng); return gesym;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
{
  record_length (doggy_leng); return lessthansym;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
{
  record_length (doggy_leng); return greaterthansym;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
{
  record_length (doggy_leng); return shlsym;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
{
  record_length (doggy_leng); return shrsym;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
{
  record_length (doggy_leng); return slashsym;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
{
  record_length (doggy_leng); return percentsym;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
{
  record_length (doggy_leng); return ampersandsym;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
{
  record_length (doggy_leng); return plussym;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
{
  record_length (doggy_leng); return openquotesym;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
{
  record_length (doggy_leng); return CONSsym;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
{
  record_length (doggy_leng); return IFsym;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
{
  record_length (doggy_leng); return THENsym;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
{
  record_length (doggy_leng); return ELSIFsym;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
{
  record_length (doggy_leng); return ELSEsym;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
{
  record_length (doggy_leng); return FIsym;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
{
  record_length (doggy_leng); return exclaimsym;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
{
  record_length (doggy_leng); return tildasym;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
{
  record_length (doggy_leng); return arrowsym;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
{
  record_length (doggy_leng); return WHEREsym;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
{
  record_length (doggy_leng); return RULESsym;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
{
  record_symbol (doggy_leng,doggy_text);  skip_comment ("*/");
}
	YY_BREAK
case 57:
YY_RULE_SETUP
{
  record_symbol (doggy_leng,doggy_text);  skip_comment ("\n");
}
	YY_BREAK
case 58:
YY_RULE_SETUP
{
  doggy_lval.Boolsym_type = Encode_Bool(doggy_text);
  record_length (doggy_leng); return Boolsym;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
{
  doggy_lval.Identsym_type = Encode_Ident(doggy_text);
  record_length (doggy_leng); return Identsym;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
{
  doggy_lval.Intsym_type = Encode_Int(doggy_text);
  record_length (doggy_leng); return Intsym;
}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
{
  doggy_lval.Stringsym_type = Encode_String(doggy_text);
  record_length (doggy_leng); return Stringsym;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
{
  record_length (doggy_leng);
  record_symbol (doggy_leng,doggy_text);
  update_line_and_fname(doggy_text);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
{
  record_length (doggy_leng);
  record_symbol (doggy_leng,doggy_text);
  update_line_and_fname(doggy_text);
}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
{
  record_length (doggy_leng);
  record_symbol (doggy_leng,doggy_text);
  new_input_line();
}
	YY_BREAK
case 65:
YY_RULE_SETUP
{
  record_length (doggy_leng);
  record_symbol (doggy_leng,doggy_text);
}
	YY_BREAK
case 66:
YY_RULE_SETUP
{ return NONSENSE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed doggy_in at a new source and called
			 * doggy_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = doggy_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( doggy_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * doggy_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of doggy_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					doggy_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			doggy_restart(doggy_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) doggy_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 190 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 190 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 189);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up doggy_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					doggy_restart(doggy_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( doggy_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve doggy_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void doggy_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        doggy_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            doggy__create_buffer(doggy_in,YY_BUF_SIZE );
	}

	doggy__init_buffer(YY_CURRENT_BUFFER,input_file );
	doggy__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void doggy__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		doggy_pop_buffer_state();
	 *		doggy_push_buffer_state(new_buffer);
     */
	doggy_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	doggy__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (doggy_wrap()) processing, but the only time this flag
	 * is looked at is after doggy_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void doggy__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	doggy_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE doggy__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) doggy_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in doggy__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) doggy_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in doggy__create_buffer()" );

	b->yy_is_our_buffer = 1;

	doggy__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with doggy__create_buffer()
 * 
 */
    void doggy__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		doggy_free((void *) b->yy_ch_buf  );

	doggy_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a doggy_restart() or at EOF.
 */
    static void doggy__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	doggy__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then doggy__init_buffer was _probably_
     * called from doggy_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void doggy__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		doggy__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void doggy_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	doggy_ensure_buffer_stack();

	/* This block is copied from doggy__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from doggy__switch_to_buffer. */
	doggy__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void doggy_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	doggy__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		doggy__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void doggy_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)doggy_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in doggy_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)doggy_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in doggy_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE doggy__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) doggy_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in doggy__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	doggy__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to doggy_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       doggy__scan_bytes() instead.
 */
YY_BUFFER_STATE doggy__scan_string (yyconst char * yystr )
{
    
	return doggy__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to doggy_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE doggy__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) doggy_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in doggy__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = doggy__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in doggy__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up doggy_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		doggy_text[doggy_leng] = (yy_hold_char); \
		(yy_c_buf_p) = doggy_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		doggy_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int doggy_get_lineno  (void)
{
        
    return doggy_lineno;
}

/** Get the input stream.
 * 
 */
FILE *doggy_get_in  (void)
{
        return doggy_in;
}

/** Get the output stream.
 * 
 */
FILE *doggy_get_out  (void)
{
        return doggy_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t doggy_get_leng  (void)
{
        return doggy_leng;
}

/** Get the current token.
 * 
 */

char *doggy_get_text  (void)
{
        return doggy_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void doggy_set_lineno (int  _line_number )
{
    
    doggy_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see doggy__switch_to_buffer
 */
void doggy_set_in (FILE *  _in_str )
{
        doggy_in = _in_str ;
}

void doggy_set_out (FILE *  _out_str )
{
        doggy_out = _out_str ;
}

int doggy_get_debug  (void)
{
        return doggy__flex_debug;
}

void doggy_set_debug (int  _bdebug )
{
        doggy__flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from doggy_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    doggy_in = stdin;
    doggy_out = stdout;
#else
    doggy_in = (FILE *) 0;
    doggy_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * doggy_lex_init()
     */
    return 0;
}

/* doggy_lex_destroy is for both reentrant and non-reentrant scanners. */
int doggy_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		doggy__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		doggy_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	doggy_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * doggy_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *doggy_alloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *doggy_realloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void doggy_free (void * ptr )
{
			free( (char *) ptr );	/* see doggy_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

int doggy_wrap()
{ return 1; }

void doggy_error(char *s)
{ if (Front_Parse_Error) Front_Parse_Error (s, doggy_text);
}

