
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer egg__create_buffer
#define yy_delete_buffer egg__delete_buffer
#define yy_flex_debug egg__flex_debug
#define yy_init_buffer egg__init_buffer
#define yy_flush_buffer egg__flush_buffer
#define yy_load_buffer_state egg__load_buffer_state
#define yy_switch_to_buffer egg__switch_to_buffer
#define yyin egg_in
#define yyleng egg_leng
#define yylex egg_lex
#define yylineno egg_lineno
#define yyout egg_out
#define yyrestart egg_restart
#define yytext egg_text
#define yywrap egg_wrap
#define yyalloc egg_alloc
#define yyrealloc egg_realloc
#define yyfree egg_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE egg_restart(egg_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t egg_leng;

extern FILE *egg_in, *egg_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up egg_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up egg_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via egg_restart()), so that the user can continue scanning by
	 * just pointing egg_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when egg_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t egg_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow egg_wrap()'s to do buffer switches
 * instead of setting up a fresh egg_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void egg_restart (FILE *input_file  );
void egg__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE egg__create_buffer (FILE *file,int size  );
void egg__delete_buffer (YY_BUFFER_STATE b  );
void egg__flush_buffer (YY_BUFFER_STATE b  );
void egg_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void egg_pop_buffer_state (void );

static void egg_ensure_buffer_stack (void );
static void egg__load_buffer_state (void );
static void egg__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER egg__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE egg__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE egg__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE egg__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *egg_alloc (yy_size_t  );
void *egg_realloc (void *,yy_size_t  );
void egg_free (void *  );

#define yy_new_buffer egg__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        egg_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            egg__create_buffer(egg_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        egg_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            egg__create_buffer(egg_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *egg_in = (FILE *) 0, *egg_out = (FILE *) 0;

typedef int yy_state_type;

extern int egg_lineno;

int egg_lineno = 1;

extern char *egg_text;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr egg_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up egg_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	egg_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[580] =
    {   0,
        0,    0,   75,   73,   72,   71,   73,   73,   73,   60,
       61,   52,   73,   53,   64,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   63,   65,   72,   73,   72,   71,
        0,   67,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   66,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   72,    0,   70,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   68,   68,   68,   68,   58,   68,
       68,   68,   70,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    1,   68,   68,   68,   68,   59,   51,   68,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    3,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,   68,
       55,   54,   62,   68,   69,    0,    0,    0,    0,   27,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    4,   68,   68,   69,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   13,
        0,    0,    0,    0,    0,    0,    0,   28,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   68,   56,
        0,    0,    0,    0,    0,    0,    0,   21,    0,    0,
        0,    0,    0,    5,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   14,    0,    0,    0,
       57,    0,    0,    0,    0,    0,   50,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   22,    0,    0,    0,    0,    0,    6,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   17,   49,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   11,    0,    0,    0,    0,    0,    0,
        0,    0,   15,   25,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   18,    0,    0,
        0,    0,    9,    0,   19,    0,    0,    0,    0,    0,
        0,   23,    0,    0,    0,    0,   12,    0,    0,    0,
        0,    0,    0,    0,    0,   16,   26,    0,    0,    0,
        7,    0,    0,    0,    0,   41,   47,    0,    0,    0,
        0,   10,    0,   20,    0,    0,    0,    0,    0,    0,

       24,    0,    0,    0,    0,    0,   29,    0,    0,    0,
        0,    0,    8,    0,    0,    0,    0,   42,   48,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   30,    0,    0,    0,    0,    0,   35,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   36,    0,
        0,    0,    0,    0,    0,    0,   39,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   40,    0,    0,    0,    0,   33,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   34,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   31,    0,    0,    0,    0,
        0,    0,   37,   43,    0,    0,   32,    0,    0,    0,
       38,   44,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   45,    0,   46,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    6,    7,    1,    8,    1,    9,   10,
       11,   12,    1,   13,    1,    1,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   16,   16,    1,   17,    1,
       18,    1,    9,    1,   19,   20,   20,   21,   22,   20,
       23,   24,   25,   24,   26,   27,   28,   24,   29,   30,
       24,   31,   32,   33,   34,   24,   24,   35,   24,   24,
        1,   36,    1,    1,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   24,   45,   24,   46,   47,   48,   49,
       50,   51,   24,   52,   53,   54,   55,   56,   57,   58,
       59,   24,   60,    1,   61,    1,    1,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62
    } ;

static yyconst YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    3,    1,
        1,    1,    1,    1,    4,    5,    1,    1,    5,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    7,    3,    6,    4,    4,    5,
        5,    5,    4,    6,    6,    6,    6,    6,    7,    6,
        6,    7,    6,    7,    6,    7,    6,    7,    6,    1,
        1,    8
    } ;

static yyconst flex_uint16_t yy_base[586] =
    {   0,
        0,   61,  673,  674,   62,  674,  669,   59,   77,  674,
      674,  674,  659,  674,  674,    0,  625,  617,  630,  615,
      624,  615,  611,  625,  674,  674,   65,   69,   72,  674,
       72,  674,   55,  635,  619,  602,  607,  617,   46,  627,
      618,   25,  602,  101,  610,  674,    0,  600,  600,  597,
      600,  590,  595,  605,  594,   79,   80,    0,  600,   79,
        0,  611,  603,  591,  591,  598,  608,  585,  604,  584,
       39,  596,  592,  606,  590,  573,  578,   68,  599,  590,
       38,  574,  582,  581,  586,  573,  584,  566,    0,  566,
      566,  569,    0,  568,  106,  138,  579,  568,  562,  558,

      563,  589,  557,   89,  571,  554,  562,  578,  552,  571,
      563,  551,  551,  569,  546,  565,  545,   49,  557,  553,
      550,  674,  554,  540,  544,  539,    0,    0,  544,  546,
       98,    0,   96,  549,  544,  534,  530,  546,  544,  552,
       95,  532,  537,  529,  535,  674,  539,  528,  522,  518,
      550,  518,  104,  532,  515,  523,  539,  513,  674,  518,
        0,    0,    0,  515,    0,  505,   82,  510,  508,  674,
      507,  537,  514,  526,  518,  503,  503,  500,  504,  507,
      497,  118,  511,  506,  496,  509,  507,  515,  105,  495,
      500,  492,  498,  674,  497,  494,    0,  486,  484,  496,

      496,  480,  473,  473,  488,  507,  474,  477,  484,  674,
      483,  471,  470,  464,   92,  469,  467,  674,  497,  474,
      486,  478,  463,  463,  460,  464,  467,  457,  468,    0,
      456,  462,  478,  451,  459,  455,  451,  475,  463,  461,
      443,  448,  447,  436,  456,  442,  440,  452,  452,  436,
      430,  445,  464,  431,  434,  441,  674,  440,  428,  427,
        0,  437,  429,  435,  431,  425,  674,  422,  428,  140,
      425,  420,  419,  415,  420,  423,  414,  420,  436,  409,
      417,  410,  434,  422,  420,  402,  407,  406,  674,  416,
      400,  408,  398,  400,  400,  406,  398,  404,  393,  390,

      390,  389,  403,  387,  674,  397,  396,  388,  394,  390,
      384,  381,  387,  141,  384,  379,  378,  374,  383,  373,
      372,  371,  374,  674,  369,  380,  380,  369,  380,  358,
      357,  363,  674,  361,  360,  368,  358,  360,  360,  366,
      358,  364,  353,  350,  350,  349,  363,  347,  357,  353,
      338,  358,  342,  341,  674,  346,  337,  337,  342,  341,
      335,  674,  334,  333,  332,  335,  674,  330,  341,  341,
      330,  341,  319,  318,  324,  674,  322,  324,  325,  328,
      674,  326,  332,  318,  326,  674,  674,  308,  321,  306,
      326,  310,  309,  674,  314,  305,  305,  310,  309,  303,

      674,  306,  317,  311,  302,  299,  674,  302,  301,  298,
      299,  302,  674,  300,  306,  292,  300,  674,  674,  282,
      303,  307,  301,  288,  298,  293,  297,  284,  295,  289,
      280,  277,  674,  280,  279,  294,  303,  292,  674,  269,
      273,  296,  283,  287,  281,  268,  278,  273,  277,  291,
      282,  289,  265,  255,  267,  275,  284,  273,  674,  250,
      254,  277,  271,  263,  269,  248,  674,  255,  274,  265,
      272,  248,  238,  250,  253,  249,  251,  238,  237,  255,
      247,  253,  232,  674,  239,  240,  229,  238,  674,  223,
      239,  235,  237,  224,  223,  221,  222,  219,  215,  227,

      216,  225,  674,  210,  215,  214,  213,  201,  209,  210,
      207,  203,  207,  216,  205,  204,  203,  202,  201,  189,
      209,  193,  207,  207,  195,  204,  193,  192,  186,  179,
      184,  196,  197,  181,  195,  195,  172,  182,  170,  181,
      174,  167,  172,  184,  175,  674,  174,  171,  161,  171,
      159,  170,  674,  674,  157,  152,  674,  149,  146,  141,
      674,  674,  122,  120,  128,  131,  117,  115,  128,  112,
      104,   93,   98,   77,   44,  674,   41,  674,  674,  181,
      185,  191,  198,  203,  208
    } ;

static yyconst flex_int16_t yy_def[586] =
    {   0,
      579,    1,  579,  579,  579,  579,  579,  580,  579,  579,
      579,  579,  579,  579,  579,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  579,  579,  579,  579,  579,  579,
      580,  579,  582,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  579,  579,  583,  579,  580,
      584,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  581,  581,  581,  581,  581,  581,
      581,  581,  583,  579,  580,  580,  579,  579,  579,  579,

      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  581,  581,  581,  581,  581,  581,  581,  579,
      580,   96,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  581,
      581,  581,  581,  581,  585,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  581,  581,  585,  579,  579,  579,

      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  581,  581,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      581,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,

      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,

      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,

      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,    0,  579,
      579,  579,  579,  579,  579
    } ;

static yyconst flex_uint16_t yy_nxt[737] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,    4,   10,
       11,    4,   12,   13,    4,    4,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,    4,   16,   16,   16,   16,
       17,   18,   19,   20,   16,   21,   16,   16,   16,   16,
       22,   16,   16,   16,   23,   16,   24,   16,   16,   25,
       26,    4,   27,   29,   32,   29,   56,   28,   29,   60,
       58,   57,   58,   29,   67,   29,  106,   32,   71,   72,
       56,   58,   29,   58,   32,   57,  155,   68,  578,   61,
      107,  118,  119,   95,   33,   34,  114,   35,   36,   37,

      156,   38,  577,   32,   39,   40,   41,   33,   42,  115,
       43,   32,   61,   44,   33,   59,  140,  166,   45,   74,
      131,   75,   76,   77,  576,  141,   59,  167,   78,   79,
       80,  188,   81,   33,   82,  199,  200,  175,  176,  214,
      189,   33,   83,   32,  177,  247,  248,  222,  223,  215,
      575,  574,  132,  132,  224,  573,  132,  132,  132,  132,
      298,  342,  299,  343,  572,  571,  570,  569,  568,  567,
      566,  300,  344,   33,  565,  132,  132,  132,  132,  132,
      132,   31,  564,   31,   31,   31,   31,   31,   47,   47,
       47,   47,   31,   31,   31,  563,  562,   31,   93,  561,

       93,   93,   93,   93,   93,   93,   96,   96,  197,  560,
      197,  197,  197,  197,  197,  197,  559,  558,  557,  556,
      555,  554,  553,  552,  551,  550,  549,  548,  547,  546,
      545,  544,  543,  542,  541,  540,  539,  538,  537,  536,
      535,  534,  533,  532,  531,  530,  529,  528,  527,  526,
      525,  524,  523,  522,  521,  520,  519,  518,  517,  516,
      515,  514,  513,  512,  511,  510,  509,  508,  507,  506,
      505,  504,  503,  502,  501,  500,  499,  498,  497,  496,
      495,  494,  493,  492,  491,  490,  489,  488,  487,  486,
      485,  484,  483,  482,  481,  480,  479,  478,  477,  476,

      475,  474,  473,  472,  471,  470,  469,  468,  467,  466,
      465,  464,  463,  462,  461,  460,  459,  458,  457,  456,
      455,  454,  453,  452,  451,  450,  449,  448,  447,  446,
      445,  444,  443,  442,  441,  440,  439,  438,  437,  436,
      435,  434,  433,  432,  431,  430,  429,  428,  427,  426,
      425,  424,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  409,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  381,  380,  379,  378,  377,  376,

      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,

      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  221,  220,  219,  218,  217,  216,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  198,  196,  195,  194,  193,  192,  191,  190,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      174,  173,  172,  171,  170,  169,  168,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  154,  153,  152,  151,

      150,  149,  148,  147,  146,  145,  144,  143,  142,  139,
      138,  137,  136,  135,  134,  133,  130,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  117,  116,  113,
      112,  111,  110,  109,  108,  105,  104,  103,  102,  101,
      100,   99,   98,   97,   94,   92,   91,   90,   89,   88,
       87,   86,   85,   84,   73,   70,   69,   66,   65,   64,
       63,   62,   55,   54,   53,   52,   51,   50,   49,   48,
       46,   30,  579,    3,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,

      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579
    } ;

static yyconst flex_int16_t yy_chk[737] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    5,    8,    5,   27,    2,   27,   33,
       28,   27,   28,   29,   39,   29,   71,   31,   42,   42,
       56,   57,   56,   57,   60,   56,  118,   39,  577,   33,
       71,   81,   81,   60,    8,    9,   78,    9,    9,    9,

      118,    9,  575,  131,    9,    9,    9,   31,    9,   78,
        9,   95,   33,    9,   60,   28,  104,  133,    9,   44,
       95,   44,   44,   44,  574,  104,   57,  133,   44,   44,
       44,  153,   44,  131,   44,  167,  167,  141,  141,  182,
      153,   95,   44,   96,  141,  215,  215,  189,  189,  182,
      573,  572,   96,   96,  189,  571,   96,   96,   96,   96,
      270,  314,  270,  314,  570,  569,  568,  567,  566,  565,
      564,  270,  314,   96,  563,   96,   96,   96,   96,   96,
       96,  580,  560,  580,  580,  580,  580,  580,  581,  581,
      581,  581,  582,  582,  582,  559,  558,  582,  583,  556,

      583,  583,  583,  583,  583,  583,  584,  584,  585,  555,
      585,  585,  585,  585,  585,  585,  552,  551,  550,  549,
      548,  547,  545,  544,  543,  542,  541,  540,  539,  538,
      537,  536,  535,  534,  533,  532,  531,  530,  529,  528,
      527,  526,  525,  524,  523,  522,  521,  520,  519,  518,
      517,  516,  515,  514,  513,  512,  511,  510,  509,  508,
      507,  506,  505,  504,  502,  501,  500,  499,  498,  497,
      496,  495,  494,  493,  492,  491,  490,  488,  487,  486,
      485,  483,  482,  481,  480,  479,  478,  477,  476,  475,
      474,  473,  472,  471,  470,  469,  468,  466,  465,  464,

      463,  462,  461,  460,  458,  457,  456,  455,  454,  453,
      452,  451,  450,  449,  448,  447,  446,  445,  444,  443,
      442,  441,  440,  438,  437,  436,  435,  434,  432,  431,
      430,  429,  428,  427,  426,  425,  424,  423,  422,  421,
      420,  417,  416,  415,  414,  412,  411,  410,  409,  408,
      406,  405,  404,  403,  402,  400,  399,  398,  397,  396,
      395,  393,  392,  391,  390,  389,  388,  385,  384,  383,
      382,  380,  379,  378,  377,  375,  374,  373,  372,  371,
      370,  369,  368,  366,  365,  364,  363,  361,  360,  359,
      358,  357,  356,  354,  353,  352,  351,  350,  349,  348,

      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  332,  331,  330,  329,  328,  327,
      326,  325,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  313,  312,  311,  310,  309,  308,  307,  306,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  269,  268,  266,  265,  264,  263,  262,  260,
      259,  258,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,

      238,  237,  236,  235,  234,  233,  232,  231,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  217,
      216,  214,  213,  212,  211,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  196,  195,  193,
      192,  191,  190,  188,  187,  186,  185,  184,  183,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      169,  168,  166,  164,  160,  158,  157,  156,  155,  154,
      152,  151,  150,  149,  148,  147,  145,  144,  143,  142,
      140,  139,  138,  137,  136,  135,  134,  130,  129,  126,
      125,  124,  123,  121,  120,  119,  117,  116,  115,  114,

      113,  112,  111,  110,  109,  108,  107,  106,  105,  103,
      102,  101,  100,   99,   98,   97,   94,   92,   91,   90,
       88,   87,   86,   85,   84,   83,   82,   80,   79,   77,
       76,   75,   74,   73,   72,   70,   69,   68,   67,   66,
       65,   64,   63,   62,   59,   55,   54,   53,   52,   51,
       50,   49,   48,   45,   43,   41,   40,   38,   37,   36,
       35,   34,   24,   23,   22,   21,   20,   19,   18,   17,
       13,    7,    3,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,

      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int egg__flex_debug;
int egg__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *egg_text;
#define fe_parser_input egg_in
#include "egg.h"
#include "front/support.h"
#include "front/scan_support.h"
#include "front/parse_support.h"
#include "egg_y.h"
#undef YYLMAX
#define YYLMAX		(8*1024-1)

int egg_state_stack_depth=0;

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int egg_lex_destroy (void );

int egg_get_debug (void );

void egg_set_debug (int debug_flag  );

YY_EXTRA_TYPE egg_get_extra (void );

void egg_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *egg_get_in (void );

void egg_set_in  (FILE * _in_str  );

FILE *egg_get_out (void );

void egg_set_out  (FILE * _out_str  );

yy_size_t egg_get_leng (void );

char *egg_get_text (void );

int egg_get_lineno (void );

void egg_set_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int egg_wrap (void );
#else
extern int egg_wrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( egg_text, egg_leng, 1, egg_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( egg_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( egg_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, egg_in))==0 && ferror(egg_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(egg_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int egg_lex (void);

#define YY_DECL int egg_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after egg_text and egg_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( egg_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(egg_text[egg_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! egg_in )
			egg_in = stdin;

		if ( ! egg_out )
			egg_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			egg_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				egg__create_buffer(egg_in,YY_BUF_SIZE );
		}

		egg__load_buffer_state( );
		}

	{

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of egg_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 580 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 674 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{
  return hole_egg;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
{
  return start_egg;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
{
  return hole_Uses;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
{
  return start_Uses;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
{
  return hole_Strings;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
{
  return start_Strings;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
{
  return hole_Declarations;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
{
  return start_Declarations;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
{
  return hole_Declaration;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
{
  return start_Declaration;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
{
  return hole_Expression;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
{
  return start_Expression;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
{
  return hole_Params;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
{
  return start_Params;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
{
  return hole_Statements;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
{
  return start_Statements;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
{
  return hole_Statement;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
{
  return start_Statement;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
{
  return hole_MessageKind;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
{
  return start_MessageKind;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
{
  return hole_Message;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
{
  return start_Message;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
{
  return hole_SubMessages;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
{
  return start_SubMessages;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
{
  return hole_SubMessage;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
{
  return start_SubMessage;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
{
  return hole_Group;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
{
  return start_Group;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
{
  return hole_OPTMORE_Group;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
{
  return start_OPTMORE_Group;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
{
  return hole_ALT_Stringsym_SEP_commasym;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
{
  return start_ALT_Stringsym_SEP_commasym;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
{
  return hole_OPTMORE_Declaration;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
{
  return start_OPTMORE_Declaration;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
{
  return hole_MORE_Expression;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
{
  return start_MORE_Expression;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
{
  return hole_ALT_Expression_SEP_commasym;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
{
  return start_ALT_Expression_SEP_commasym;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
{
  return hole_OPTMORE_Statement;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
{
  return start_OPTMORE_Statement;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
{
  return hole_OPT_fatalsym;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
{
  return start_OPT_fatalsym;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
{
  return hole_ALT_SubMessage_SEP_commasym;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
{
  return start_ALT_SubMessage_SEP_commasym;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
{
  return hole_OPT_openparsym_Identsym_closeparsym;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
{
  return start_OPT_openparsym_Identsym_closeparsym;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
{
  return hole_OPT_groupsym;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
{
  return start_OPT_groupsym;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
{
  egg_lval.Stringsym_type = (String)Get_sub_tree();
  return Stringsym;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
{
  egg_lval.Identsym_type = (Ident)Get_sub_tree();
  return Identsym;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
{
  record_length (egg_leng); return usessym;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
{
  record_length (egg_leng); return commasym;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
{
  record_length (egg_leng); return semicolonsym;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
{
  record_length (egg_leng); return fatalsym;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
{
  record_length (egg_leng); return errorsym;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
{
  record_length (egg_leng); return warningsym;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
{
  record_length (egg_leng); return disabledsym;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
{
  record_length (egg_leng); return keysym;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
{
  record_length (egg_leng); return postsym;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
{
  record_length (egg_leng); return openparsym;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
{
  record_length (egg_leng); return closeparsym;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
{
  record_length (egg_leng); return groupsym;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
{
  record_length (egg_leng); return openchainsym;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
{
  record_length (egg_leng); return equalssym;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
{
  record_length (egg_leng); return closechainsym;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
{
  record_symbol (egg_leng,egg_text);  skip_comment ("*/");
}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
{
  egg_lval.Stringsym_type = Encode_String(egg_text);
  record_length (egg_leng); return Stringsym;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
{
  egg_lval.Identsym_type = Encode_Ident(egg_text);
  record_length (egg_leng); return Identsym;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
{
  record_length (egg_leng);
  record_symbol (egg_leng,egg_text);
  update_line_and_fname(egg_text);
}
	YY_BREAK
case 70:
YY_RULE_SETUP
{
  record_length (egg_leng);
  record_symbol (egg_leng,egg_text);
  update_line_and_fname(egg_text);
}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
{
  record_length (egg_leng);
  record_symbol (egg_leng,egg_text);
  new_input_line();
}
	YY_BREAK
case 72:
YY_RULE_SETUP
{
  record_length (egg_leng);
  record_symbol (egg_leng,egg_text);
}
	YY_BREAK
case 73:
YY_RULE_SETUP
{ return NONSENSE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed egg_in at a new source and called
			 * egg_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = egg_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( egg_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * egg_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of egg_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					egg_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			egg_restart(egg_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) egg_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 580 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 580 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 579);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up egg_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					egg_restart(egg_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( egg_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve egg_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void egg_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        egg_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            egg__create_buffer(egg_in,YY_BUF_SIZE );
	}

	egg__init_buffer(YY_CURRENT_BUFFER,input_file );
	egg__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void egg__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		egg_pop_buffer_state();
	 *		egg_push_buffer_state(new_buffer);
     */
	egg_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	egg__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (egg_wrap()) processing, but the only time this flag
	 * is looked at is after egg_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void egg__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	egg_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE egg__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) egg_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in egg__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) egg_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in egg__create_buffer()" );

	b->yy_is_our_buffer = 1;

	egg__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with egg__create_buffer()
 * 
 */
    void egg__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		egg_free((void *) b->yy_ch_buf  );

	egg_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a egg_restart() or at EOF.
 */
    static void egg__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	egg__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then egg__init_buffer was _probably_
     * called from egg_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void egg__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		egg__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void egg_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	egg_ensure_buffer_stack();

	/* This block is copied from egg__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from egg__switch_to_buffer. */
	egg__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void egg_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	egg__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		egg__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void egg_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)egg_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in egg_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)egg_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in egg_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE egg__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) egg_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in egg__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	egg__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to egg_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       egg__scan_bytes() instead.
 */
YY_BUFFER_STATE egg__scan_string (yyconst char * yystr )
{
    
	return egg__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to egg_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE egg__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) egg_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in egg__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = egg__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in egg__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up egg_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		egg_text[egg_leng] = (yy_hold_char); \
		(yy_c_buf_p) = egg_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		egg_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int egg_get_lineno  (void)
{
        
    return egg_lineno;
}

/** Get the input stream.
 * 
 */
FILE *egg_get_in  (void)
{
        return egg_in;
}

/** Get the output stream.
 * 
 */
FILE *egg_get_out  (void)
{
        return egg_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t egg_get_leng  (void)
{
        return egg_leng;
}

/** Get the current token.
 * 
 */

char *egg_get_text  (void)
{
        return egg_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void egg_set_lineno (int  _line_number )
{
    
    egg_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see egg__switch_to_buffer
 */
void egg_set_in (FILE *  _in_str )
{
        egg_in = _in_str ;
}

void egg_set_out (FILE *  _out_str )
{
        egg_out = _out_str ;
}

int egg_get_debug  (void)
{
        return egg__flex_debug;
}

void egg_set_debug (int  _bdebug )
{
        egg__flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from egg_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    egg_in = stdin;
    egg_out = stdout;
#else
    egg_in = (FILE *) 0;
    egg_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * egg_lex_init()
     */
    return 0;
}

/* egg_lex_destroy is for both reentrant and non-reentrant scanners. */
int egg_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		egg__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		egg_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	egg_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * egg_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *egg_alloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *egg_realloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void egg_free (void * ptr )
{
			free( (char *) ptr );	/* see egg_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

int egg_wrap()
{ return 1; }

void egg_error(char *s)
{ if (Front_Parse_Error) Front_Parse_Error (s, egg_text);
}

