#!/bin/sh -p
# Copyright (C) 2000-2005 Philips Electronics N.V.
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

if [ $# = 0 ]; then
    echo "add_license [ -gpl | -lgpl ] file..."
    exit 1;
fi

if [ ! -f gpl.comment ]; then
    echo "add_license: error: could not find gpl.comment"
    exit 1;
fi
if [ ! -f lgpl.comment ]; then
    echo "add_license: error: could not find lgpl.comment"
    exit 1;
fi

license=detect
while [ $# != 0 ]; do
    case $1 in
    -gpl)
            license=gpl;;
    -lgpl)
            license=lgpl;;
    *)
            input="$input $1";;
    esac
    shift
done
error=0

cat > license.awk <<EOF
BEGIN {
  disabled=0;
  lines=0;
}

/Copyright/ {
  if(lines<=1) {
    disabled=1;
    match(\$0,/(.*)Copyright/,arr)
    comment_string=arr[1];
    comment=\$1
  }
}

{
  if (disabled && \$1!=comment) {
    disabled=0;
    while ((getline line < ARGV[2]) > 0) {
      print comment_string line
    }
  } 
  if (!disabled) print \$0;
  lines++;
}
EOF

for f in $input; do
    cp $f $f~
    if ! ( head -2 $f | grep Copyright > /dev/null 2>&1); then
        echo "add_license: error: file \"$f\" does not contain copyright" 1>&2
        error=1;
    else
        if [ "$license" = "detect" ]; then
            if grep -e "GNU[ ]Lesser" $f > /dev/null 2>&1; then
                license=lgpl;
            elif grep -e "GNU[ ]General" $f > /dev/null 2>&1; then
                license=gpl;
            else
                echo "add_license: error: unable to detect license in file \"$f\"" 1>&2
                error=1;
            fi
        fi
        if [ "$license" != "detect" ]; then
            gawk -f license.awk $f~ $license.comment > $f
        fi
    fi
done

rm license.awk

if [ $error != 0 ]; then
    exit 1;
fi
